/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "specif.h"

bool_t
xdr_Chaine(XDR *xdrs, Chaine *objp)
{

	if (!xdr_pointer(xdrs, (char **)&objp->car, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}
