/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SPECIF_H_RPCGEN
#define _SPECIF_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct Chaine {
	char *car;
};
typedef struct Chaine Chaine;
#ifdef __cplusplus
extern "C" bool_t xdr_Chaine(XDR *, Chaine*);
#elif __STDC__
extern  bool_t xdr_Chaine(XDR *, Chaine*);
#else /* Old Style C */
bool_t xdr_Chaine();
#endif /* Old Style C */


#define FILEMANUPULATION ((rpc_uint)0x2fffffff)
#define FILE_1 ((rpc_uint)1)

#ifdef __cplusplus
#define chercher ((rpc_uint)1)
extern "C" int * chercher_1(Chaine *, CLIENT *);
extern "C" int * chercher_1_svc(Chaine *, struct svc_req *);
#define supprimer ((rpc_uint)2)
extern "C" int * supprimer_1(Chaine *, CLIENT *);
extern "C" int * supprimer_1_svc(Chaine *, struct svc_req *);

#elif __STDC__
#define chercher ((rpc_uint)1)
extern  int * chercher_1(Chaine *, CLIENT *);
extern  int * chercher_1_svc(Chaine *, struct svc_req *);
#define supprimer ((rpc_uint)2)
extern  int * supprimer_1(Chaine *, CLIENT *);
extern  int * supprimer_1_svc(Chaine *, struct svc_req *);

#else /* Old Style C */
#define chercher ((rpc_uint)1)
extern  int * chercher_1();
extern  int * chercher_1_svc();
#define supprimer ((rpc_uint)2)
extern  int * supprimer_1();
extern  int * supprimer_1_svc();
#endif /* Old Style C */

#endif /* !_SPECIF_H_RPCGEN */
