/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "specif.h"


void
filemanupulation_1( char* host )
{
	CLIENT *clnt;
	int  *result_1;
	Chaine  chercher_1_arg;
	int  *result_2;
	Chaine  supprimer_1_arg;
	clnt = clnt_create(host, FILEMANUPULATION, FILE_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = chercher_1(&chercher_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_2 = supprimer_1(&supprimer_1_arg, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );
}


main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	filemanupulation_1( host );
}
