/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "specif.h"

int *
chercher_1_svc(Chaine *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
supprimer_1_svc(Chaine *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}
